### ISSUE TITLE
It's not a problem, it's a request

### ISSUE THREAD

**Issue by diegotfcastro88** [jamesslinger/YTDLAudio#1]
congratulations on the development, I think it turned out amazing, could you put the option to also download the video?

Thanks

**Comment by jamesslinger** [comment]
Hi! thank you for the feedback, it's my first ever so very much appreciated!

It's certainly possible to put together something to download the videos, however It would require quite a bit of time to refactor the code to add it in. There is also the issue of memory capacity and storage as my current server setup is very minimal so would cost me a fair amount of money to upgrade my account to facilitate this.

So at the moment I don't think I'll have the time or the money to do this, but in the future it's certainly something I will consider doing.

Thanks,
James
